joint_limits:
  shoulder_pan_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0 #330.0 # #뉴턴미터(NM)
    max_position: !degrees  170.0
    max_velocity: !degrees  180.0
    min_position: !degrees -170.0
  shoulder_lift_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0 #330.0 #56.0
    max_position: !degrees  180.0
    max_velocity: !degrees  120.0
    min_position: !degrees  -55.0
  elbow_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0 #330.0 #28.0
    max_position: !degrees  213.0
    max_velocity: !degrees  180.0
    min_position: !degrees -70.0
  wrist_1_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 5.0 #330.0 # 
    max_position: !degrees  190.0
    max_velocity: !degrees  180.0
    min_position: !degrees -190.0
  wrist_2_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 5.6 #330.0 #
    max_position: !degrees  135.0
    max_velocity: !degrees  180.0
    min_position: !degrees -135.0
  wrist_3_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 2.8 #330.0 #
    max_position: !degrees  360.0
    max_velocity: !degrees  180.0
    min_position: !degrees -360.0
