mesh_files:
  base:
    visual:
      mesh:
        package: hr_description
        path: meshes/yl012/visual/base_body.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh:
        package: hr_description
        path: meshes/yl012/collision/base_body.stl

  shoulder:
    visual:
      mesh:
        package: hr_description
        path: meshes/yl012/visual/lower_frame.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh:
        package: hr_description
        path: meshes/yl012/collision/lower_frame.stl

  upper_arm:
    visual:
      mesh:
        package: hr_description
        path: meshes/yl012/visual/upper_frame.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh:
        package: hr_description
        path: meshes/yl012/collision/upper_frame.stl

  forearm:
    visual:
      mesh:
        package: hr_description
        path: meshes/yl012/visual/arm_frame.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh:
        package: hr_description
        path: meshes/yl012/collision/arm_frame.stl

  wrist_1:
    visual:
      mesh:
        package: hr_description
        path: meshes/yl012/visual/arm_pipe.stl
      origin:
        xyz: [-0.1506, 0, 0]
        rpy: [1.57079632679, 0, 0]
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh:
        package: hr_description
        path: meshes/yl012/collision/arm_pipe.stl
      origin:
        xyz: [-0.1506, 0, 0]
        rpy: [1.57079632679, 0, 0]
    visual_offset: 0

  wrist_2:
    visual:
      mesh:
        package: hr_description
        path: meshes/yl012/visual/wrist.stl
      origin:
        xyz: [0, 0, 0]
        rpy: [1.57079632679, 0, 0]
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh:
        package: hr_description
        path: meshes/yl012/collision/wrist.stl
      origin:
        xyz: [0, 0, 0]
        rpy: [1.57079632679, 0, 0]
    visual_offset: 0

  wrist_3:
    visual:
      mesh:
        package: hr_description
        path: meshes/yl012/visual/interface.stl
      origin:
        xyz: [-0.5678, 0, 0.003]
        rpy: [1.57079632679, 0, 0]
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh:
        package: hr_description
        path: meshes/yl012/collision/interface.stl
      origin:
        xyz: [-0.5678, 0, 0.003]
        rpy: [1.57079632679, 0, 0]
    visual_offset: 0