controller_manager:
  ros__parameters:
    update_rate: 500 # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    forward_position_controller:
      type: position_controllers/JointGroupPositionController
    
    conveyor_controller:  # 새로운 컨트롤러 추가
      type: position_controllers/JointPositionController

speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: tool0
    topic_name: ft_data

joint_trajectory_controller:
  ros__parameters:
    joints:
      - conveyor_to_robot_base  # 컨베이어 벨트 조인트 추가
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      conveyor_to_robot_base: { trajectory: 0.2, goal: 0.1 }  # 컨베이어 벨트 제약 조건 추가
      shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      elbow_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - conveyor_to_robot_base  # 컨베이어 벨트 조인트 추가
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      conveyor_to_robot_base: { trajectory: 0.2, goal: 0.1 }  # 컨베이어 벨트 제약 조건 추가
      shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      elbow_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

forward_velocity_controller:
  ros__parameters:
    joints:
      - conveyor_to_robot_base  # 컨베이어 벨트 조인트 추가
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: velocity

forward_position_controller:
  ros__parameters:
    joints:
      - conveyor_to_robot_base  # 컨베이어 벨트 조인트 추가
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

conveyor_controller:  # 새로운 컨베이어 컨트롤러 설정
  ros__parameters:
    joint: conveyor_to_robot_base
    interface_name: position
    pid: {p: 100.0, i: 0.01, d: 10.0}