joint_limits:
  shoulder_pan_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 3139.4 # 0.8*191.42857100*20.5
    max_position: !degrees  180.0
    max_velocity: !degrees  180.0
    min_position: !degrees -180.0
  shoulder_lift_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 3139.4 # 0.8*191.42857100*20.5
    max_position: !degrees  165.0
    max_velocity: !degrees  95.0
    min_position: !degrees  15.0
  elbow_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 3139.4 # 0.8*191.42857100*20.5
    max_position: !degrees  120.0
    max_velocity: !degrees  95.0
    min_position: !degrees  -70.0
  wrist_1_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 2524.6 # 0.8*269.72537100*11.7
    max_position: !degrees  360.0
    max_velocity: !degrees  95.0
    min_position: !degrees -360.0
  wrist_2_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 2624.7 # 0.8*280.42105300*11.7
    max_position: !degrees  120.0
    max_velocity: !degrees  100.0
    min_position: !degrees  -120.0
  wrist_3_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 1574.0 # 0.8*168.17150600*11.7
    max_position: !degrees  360.0
    max_velocity: !degrees  160.0
    min_position: !degrees -360.0
