/**:
  ros__parameters:
    robot_description_kinematics:
      hr_manipulator:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.001 #0.005
        kinematics_solver_timeout: 0.001 #0.005
        kinematics_solver_attempts: 5 #3
