mesh_files:
  base:
    visual:
      mesh: 
        package: hr_description
        path: meshes/hs220_02/visual/base_body.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh: 
        package: hr_description
        path: meshes/hs220_02/collision/base_body.stl

  shoulder:
    visual:
      mesh: 
        package: hr_description
        path : meshes/hs220_02/visual/lower_frame.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh: 
        package: hr_description
        path: meshes/hs220_02/collision/lower_frame.stl

  upper_arm:
    visual:
      mesh: 
        package: hr_description
        path : meshes/hs220_02/visual/upper_frame.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh: 
        package: hr_description
        path : meshes/hs220_02/collision/upper_frame.stl

  forearm:
    visual:
      mesh: 
        package: hr_description
        path: meshes/hs220_02/visual/arm_frame.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh: 
        package: hr_description
        path: meshes/hs220_02/collision/arm_frame.stl

  wrist_1:
    visual:
      mesh: 
        package: hr_description
        path: meshes/hs220_02/visual/arm_pipe.stl
      origin:
        xyz: [0, 0, 0]
        rpy: [1.57079632679, 1.57079632679, 0]
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh: 
        package: hr_description
        path: meshes/hs220_02/collision/arm_pipe.stl
      origin:
        xyz: [0, 0, 0]
        rpy: [1.57079632679, 1.57079632679, 0]
    visual_offset: 0

  wrist_2:
    visual:
      mesh: 
        package: hr_description
        path: meshes/hs220_02/visual/wrist_body.stl
      origin:
        xyz: [0, 0, 0]
        rpy: [1.57079632679, 0, 0]
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh: 
        package: hr_description
        path: meshes/hs220_02/collision/wrist_body.stl
      origin:
        xyz: [0, 0, 0]
        rpy: [1.57079632679, 0, 0]
    visual_offset: 0

  wrist_3:
    visual:
      mesh: 
        package: hr_description
        path: meshes/hs220_02/visual/flange.stl
      origin:
        xyz: [0, 0, 0]
        rpy: [0, 1.57079632679, 0]
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh: 
        package: hr_description
        path: meshes/hs220_02/collision/flange.stl
      origin:
        xyz: [0, 0, 0]
        rpy: [0, 1.57079632679, 0]
    visual_offset: 0
