dh_parameters:
  a1: 0.04 # additional item
  d1: 0.446
  a2: 0.445
  a3: 0.04
  d4: 0.445
  d5: 0.0     # d5 value does not exist
  d6: 0.0865

offsets:
  shoulder_offset: -0.1348
  elbow_offset: -0.1375

inertia_parameters:
  base_mass: 40.0  # This mass might be incorrect
  shoulder_mass: 68.400
  upper_arm_mass: 24.497
  upper_arm_inertia_offset: 0.175 # measured from model (not used)
  forearm_mass: 17.391
  wrist_1_mass: 8.566
  wrist_2_mass: 2.746
  wrist_3_mass: 0.485

  shoulder_radius: 0.060   
  upper_arm_radius: 0.054  
  elbow_radius: 0.060    
  forearm_radius: 0.040
  wrist_radius: 0.045

  links:
    base:
      radius: 0.075
      length: 0.038
    shoulder:
      radius: 0.075
      length: 0.178
    upperarm:
      radius: 0.075
      length: 0.24365
    forearm:
      radius: 0.075
      length: 0.2132
    wrist_1:
      radius: 0.075
      length: 0.12
    wrist_2:
      radius: 0.075
      length: 0.12
    wrist_3:
      radius: 0.032
      length: 0.04

  center_of_mass:
    shoulder_cog:
      x: 0.009
      y: 0.011
      z: 0.362
    upper_arm_cog:
      x: 0.0310
      y: 0.0108
      z: 0.6800
    forearm_cog:
      x: 0.0555
      y: 0.0018
      z: 0.9078
    wrist_1_cog:
      x: 0.3322
      y: -0.003
      z: 0.9317
    wrist_2_cog:
      x: 0.516
      y: -0.0006
      z: 0.9309
    wrist_3_cog:
      x: 0.55767
      y: -0.000001
      z: 0.9309
