mesh_files:
  base:
    visual:
      mesh:
        package: hr_description
        path: meshes/hh7/visual/base_body.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh:
        package: hr_description
        path: meshes/hh7/collision/base_body.stl

  shoulder:
    visual:
      mesh:
        package: hr_description
        path: meshes/hh7/visual/lower_frame.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh:
        package: hr_description
        path: meshes/hh7/collision/lower_frame.stl

  upper_arm:
    visual:
      mesh:
        package: hr_description
        path: meshes/hh7/visual/upper_frame.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh:
        package: hr_description
        path: meshes/hh7/collision/upper_frame.stl

  forearm:
    visual:
      mesh:
        package: hr_description
        path: meshes/hh7/visual/arm_frame.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
    collision:
      mesh:
        package: hr_description
        path: meshes/hh7/collision/arm_frame.stl

  wrist_1:
    visual:
      mesh:
        package: hr_description
        path: meshes/hh7/visual/arm_pipe.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
      origin:
        xyz: [0, 0, 0]
        rpy: [0, 0, 0]
    collision:
      mesh:
        package: hr_description
        path: meshes/hh7/collision/arm_pipe.stl
      origin:
        xyz: [0, 0, 0]
        rpy: [0, 0, 0]
    visual_offset: 0

  wrist_2:
    visual:
      mesh:
        package: hr_description
        path: meshes/hh7/visual/wrist_body.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
      origin:
        xyz: [0, 0, 0]
        rpy: [0, 0, 0]
    collision:
      mesh:
        package: hr_description
        path: meshes/hh7/collision/wrist_body.stl
      origin:
        xyz: [0, 0, 0]
        rpy: [0, 0, 0]
    visual_offset: 0

  wrist_3:
    visual:
      mesh:
        package: hr_description
        path: meshes/hh7/visual/flange.stl
      material:
        name: "blue"
        color: "0 0.4 0.8 1"
      origin:
        xyz: [0, 0, 0]
        rpy: [0, 0, 0]
    collision:
      mesh:
        package: hr_description
        path: meshes/hh7/collision/flange.stl
      origin:
        xyz: [0, 0, 0]
        rpy: [0, 0, 0]
    visual_offset: 0